# 2110573 PATTERN RECOGNITION

## **Homework 1:** Clustering and Regression

Worralop Srichainont

# Dependencies

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Data Resources

Load data

In [2]:
TRAIN_URL = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
TEST_URL = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"

train = pd.read_csv(TRAIN_URL)
test = pd.read_csv(TEST_URL)

Inspect train dataset

In [3]:
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Inspect test dataset

In [4]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

# Problem 8

What is the median age of the training set?

## Calculate Median

In [5]:
median_age = train["Age"].median()
print(f"The median age is {median_age}.")

The median age is 28.0.

## Median Filling

Initially, there are some missing value on age column.

In [6]:
train[train["Age"].isna()].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q

Fill the missing age value with the median value.

In [7]:
train["Age"] = train["Age"].fillna(median_age)

## Test Dataset Validation

Make sure to fill the missing value on test dataset too.

In [8]:
median_age = test["Age"].median()
test["Age"] = test["Age"].fillna(median_age)

# Problem 9

Some fields like 'Embarked' are categorical. They need to be converted to numbers first. We will represent S with 0, C with 1, and Q with 2.

## Convert Value

Convert categorical value on `Embarked` column from `S`, `C`, and `Q` to `0`, `1`, and `2` respectively.

- The first argument of `.loc[]` command is row selection
- The second argument of `.loc[]` command is column selection

In [9]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2

Convert categorical value on `Sex` column from `male` and `female` to `0` and `1` respectively.

In [10]:
train.loc[train["Sex"] == "male", "Sex"] = 0
train.loc[train["Sex"] == "female", "Sex"] = 1

## Calculate Mode

`mode()` returns a `Series` object rather than the single value.

In [11]:
mode_embarked = train["Embarked"].mode()[0]
print(f"The mode of embarked is {mode_embarked}.")

The mode of embarked is 0.

In [12]:
mode_sex = train["Sex"].mode()[0]
print(f"The mode of sex is {mode_sex}.")

The mode of sex is 0.

## Mode Filling

Initially, there are some missing value on embarked column.

In [13]:
train[train["Embarked"].isna()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",1,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",1,62.0,0,0,113572,80.0,B28,NaN

There is no missing value on sex column.

In [14]:
train[train["Sex"].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

Fill the missing value with mode.

In [15]:
train["Embarked"] = train["Embarked"].fillna(mode_embarked)
train["Sex"] = train["Sex"].fillna(mode_sex)

C:\Users\User\AppData\Local\Temp\ipykernel_23520\1829738021.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train["Embarked"] = train["Embarked"].fillna(mode_embarked)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\1829738021.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  train["Sex"] = train["Sex"].fillna(mode_sex)

## Test Dataset Preparation

Make sure to convert categorical values on test dataset.

In [16]:
test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2

In [17]:
test.loc[test["Sex"] == "male", "Sex"] = 0
test.loc[test["Sex"] == "female", "Sex"] = 1

Also, make sure to fill missing value on test dataset.

In [18]:
mode_embarked = test["Embarked"].mode()[0]
mode_sex = test["Sex"].mode()[0]

test["Embarked"] = test["Embarked"].fillna(mode_embarked)
test["Sex"] = test["Sex"].fillna(mode_sex)

C:\Users\User\AppData\Local\Temp\ipykernel_23520\23824165.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test["Embarked"] = test["Embarked"].fillna(mode_embarked)
C:\Users\User\AppData\Local\Temp\ipykernel_23520\23824165.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test["Sex"] = test["Sex"].fillna(mode_sex)

# Problem 10

Write a linear regression classifier using gradient descent as learned in class. Use `Pclass`, `Sex`, `Age`, and `Embarked` as input features. You can extract the features from Pandas to NumPy.

## Configurations

In [19]:
INPUT_FEATURES = ["Pclass", "Sex", "Age", "Embarked"]
OUTPUT_FEATURE = "Survived"
OUTPUT_FILENAME = "submission.csv"
ID_COLUMN = "PassengerId"

CLASSIFICATION_THRESHOLD = 0.50

## Linear Regression Model

Train a linear regression model from `scikit-learn` library.

In [20]:
# Extract data from train dataset
X = train[INPUT_FEATURES]
y = train[OUTPUT_FEATURE]

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

LinearRegression()

Use pre-trained linear regression model from the previous step for prediction on test dataset.

In [21]:
# Extract data from test dataset
X_test = test[INPUT_FEATURES]

# Input test dataset into pre-trained linear regression model.
raw_predictions = model.predict(X_test)

Create a DataFrame for the output prediction file.

In [22]:
# Initialize empty DataFrame
submission = pd.DataFrame()

# Add passenger ID column to the DataFrame
submission[ID_COLUMN] = test[ID_COLUMN]

# Add raw prediction value to the DataFrame
submission[OUTPUT_FEATURE] = raw_predictions

In [23]:
# Show the DataFrame
submission.head()

   PassengerId  Survived
0          892  0.135078
1          893  0.464538
2          894  0.184522
3          895  0.074758
4          896  0.590897

## Applying Threshold

- Since it is classification task, the predicted value has to be `0` or `1` only.
- If the predicted value is less than `0.5`, change them to `0`
- If the predicted value is more than or equal to `0.5`, change them to `1`

In [24]:
submission[OUTPUT_FEATURE] = (
    submission[OUTPUT_FEATURE] >= CLASSIFICATION_THRESHOLD
).astype(int)

In [25]:
submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

## Save As CSV file

In [26]:
submission.to_csv(OUTPUT_FILENAME, index=False)

# Problem 12

Try adding some higher order features to your training (${x_{1}}^{2}$, ${x_{1}}^{x_{2}}$, ...).
Does this model has better accuracy on the training set? How does it perform on the test set?

## Configurations

In [27]:
INPUT_FEATURES = ["Pclass", "Sex", "Age", "Embarked"]
OUTPUT_FEATURE = "Survived"
OUTPUT_FILENAME = "submission_high_order.csv"
ID_COLUMN = "PassengerId"

CLASSIFICATION_THRESHOLD = 0.50

## High Order Features

Use `PolynomialFeatures(degree=2)` to automatically calculate ${x_{1}}^{2}$ and ${x_{1}}{x_{2}}$ from the input features.

In [28]:
# Extract data from train dataset
X = train[INPUT_FEATURES]
y = train[OUTPUT_FEATURE]

# Add high order features
X_high_order = PolynomialFeatures(degree=2).fit_transform(X)

Also add high order features for test dataset too.

In [29]:
# Extract data from test dataset
X_test = test[INPUT_FEATURES]

# Add high order features
X_test_high_order = PolynomialFeatures(degree=2).fit_transform(X_test)

## Linear Regression Model

Train a linear regression model from `scikit-learn` library with high order features.

In [30]:
# Train the linear regression model with high order features.
model = LinearRegression()
model.fit(X_high_order, y)

LinearRegression()

Use pre-trained linear regression model from the previous step for prediction on test dataset.

In [31]:
# Input test dataset with high order features into pre-trained linear regression model.
raw_predictions = model.predict(X_test_high_order)

Create a DataFrame for the output prediction file.

In [32]:
# Initialize empty DataFrame
submission_high_order = pd.DataFrame()

# Add passenger ID column to the DataFrame
submission_high_order[ID_COLUMN] = test[ID_COLUMN]

# Add raw prediction value to the DataFrame
submission_high_order[OUTPUT_FEATURE] = raw_predictions

In [33]:
# Show the DataFrame
submission.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         1

## Applying Threshold

- Since it is classification task, the predicted value has to be `0` or `1` only.
- If the predicted value is less than `0.5`, change them to `0`
- If the predicted value is more than or equal to `0.5`, change them to `1`

In [34]:
submission_high_order[OUTPUT_FEATURE] = (
    submission_high_order[OUTPUT_FEATURE] >= CLASSIFICATION_THRESHOLD
).astype(int)

In [35]:
submission_high_order.head()

   PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

## Save As CSV file

In [36]:
submission_high_order.to_csv(OUTPUT_FILENAME, index=False)

# Problem 13

What happens if you reduce the amount of features to just `Sex` and `Age`?

## Configurations

In [37]:
INPUT_FEATURES = ["Sex", "Age"]
OUTPUT_FEATURE = "Survived"
OUTPUT_FILENAME = "submission_reduced.csv"
ID_COLUMN = "PassengerId"

CLASSIFICATION_THRESHOLD = 0.50

## Linear Regression Model

Train a linear regression model from `scikit-learn` library.

In [38]:
# Extract data from train dataset
X = train[INPUT_FEATURES]
y = train[OUTPUT_FEATURE]

# Train the linear regression model
model = LinearRegression()
model.fit(X, y)

LinearRegression()

Use pre-trained linear regression model from the previous step for prediction on test dataset.

In [39]:
# Extract data from test dataset
X_test = test[INPUT_FEATURES]

# Input test dataset into pre-trained linear regression model.
raw_predictions = model.predict(X_test)

Create a DataFrame for the output prediction file.

In [40]:
# Initialize empty DataFrame
submission_reduced = pd.DataFrame()

# Add passenger ID column to the DataFrame
submission_reduced[ID_COLUMN] = test[ID_COLUMN]

# Add raw prediction value to the DataFrame
submission_reduced[OUTPUT_FEATURE] = raw_predictions

In [41]:
# Show the DataFrame
submission_reduced.head()

   PassengerId  Survived
0          892  0.185495
1          893  0.727108
2          894  0.163965
3          895  0.191367
4          896  0.746681

## Applying Threshold

- Since it is classification task, the predicted value has to be `0` or `1` only.
- If the predicted value is less than `0.5`, change them to `0`
- If the predicted value is more than or equal to `0.5`, change them to `1`

In [42]:
submission_reduced[OUTPUT_FEATURE] = (
    submission_reduced[OUTPUT_FEATURE] >= CLASSIFICATION_THRESHOLD
).astype(int)

In [43]:
submission_reduced.head()

   PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

## Save As CSV file

In [44]:
submission_reduced.to_csv(OUTPUT_FILENAME, index=False)